# Generated by Django 3.2.6 on 2021-08-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kapitanat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jacht',
            name='rok_produkcji',
            field=models.IntegerField(default=2137),
        ),
        migrations.AddField(
            model_name='jacht',
            name='status',
            field=models.IntegerField(default=-1),
        ),
    ]
